DROP DATABASE M_Rental;
GO

USE M_Rental;
GO

CREATE TABLE EMPRESA(
idEmpresa INT PRIMARY KEY IDENTITY(1,1),
nomeEmpresa VARCHAR(30) NOT NULL UNIQUE
);
GO

CREATE TABLE MARCA(
idMarca INT PRIMARY KEY IDENTITY(1,1),
nomeMarca VARCHAR(30) NOT NULL UNIQUE
);
GO

CREATE TABLE CLIENTE(
idCliente INT PRIMARY KEY IDENTITY(1,1),
nomeCliente VARCHAR(30) NOT NULL,
sobrenomeCliente VARCHAR(50) NOT NULL UNIQUE,
CPF CHAR(11) NOT NULL UNIQUE,
);
GO

CREATE TABLE MODELO(
idModelo INT PRIMARY KEY IDENTITY(1,1),
idMarca INT FOREIGN KEY REFERENCES MARCA(idMarca),
nomeModelo VARCHAR(50) NOT NULL,
anoModelo DATE NOT NULL,
);
GO

CREATE TABLE VEICULO(
idVeiculo INT PRIMARY KEY IDENTITY(1,1),
idModelo INT FOREIGN KEY REFERENCES MODELO(idModelo),
idEmpresa INT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
placa CHAR(7) NOT NULL UNIQUE
);
GO

CREATE TABLE ALUGUEL(
idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
idVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
idCliente INT FOREIGN KEY REFERENCES CLIENTE(idCliente),
dataRetirada DATE NOT NULL,
dataDevolucao DATE NOT NULL,
);
GO


